- name: Ensure dependencies for secure repo access are installed
  apt:
    name:
      - apt-transport-https
      - gnupg
      - curl
    state: present
    update_cache: true
  become: yes

- name: Install Java (required for Jenkins)
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  become: yes

- name: Add Jenkins apt repository GPG key
  ansible.builtin.apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
    state: present
    filename: 'jenkins'

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  become: yes

- name: Start and enable Jenkins
  systemd:
    name: jenkins
    enabled: yes
    state: started
  become: yes

# Adding the Jenkis to the docker user group
- name: Add jenkins user to the docker group
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes

- name: Add Jenkins user to ubuntu group
  become: yes
  user:
    name: jenkins
    groups: ubuntu
    append: yes

- name: Ensure group has write access
  file:
    path: "/home/ubuntu/mern-docker-demo"
    mode: "g+rwx"
    recurse: yes

# Adding the configuration to restart jenkins after the change is made
- name: Restart Jenkins to apply group changes
  ansible.builtin.service:
    name: jenkins
    state: restarted
  become: true

