# Stating the Prometheus to pull the system metrices from node exporter every 5 seconds
global: 
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']