- name: Clone MERN repo
  git:
    repo: https://github.com/Sainjurohan/mern-docker-demo.git
    dest: /home/{{ ansible_user }}/mern-docker-demo
    version: ansible
    force: yes

# adding debug
- name: Debug contents of project directory
  command: ls -la
  args:
    chdir: /home/{{ ansible_user }}/mern-docker-demo

- name: Confirm docker-compose.yml exists
  stat:
    path: /home/{{ ansible_user }}/mern-docker-demo/docker-compose.yml
  register: compose_file_check

- name: Print result of stat check
  debug:
    var: compose_file_check.stat.exists

# - name: Copy Jenkinsfile to workspace (optional)
#   copy:
#     src: /home/{{ ansible_user }}/mern-docker-demo/Jenkinsfile
#     dest: /var/lib/jenkins/workspace/mern-project-pipeline/Jenkinsfile
#     remote_src: yes

# configuration to build the images and run containers
- name: Build Docker Images
  command: docker compose -f docker-compose.yaml build
  args:
    chdir: /home/{{ ansible_user }}/mern-docker-demo  # Change directory to where the docker-compose.yml is located

- name: Run Docker Containers
  command: docker compose -f docker-compose.yaml up -d
  args:
    chdir: /home/{{ ansible_user }}/mern-docker-demo

